name: Deploy natives
on:
  push:
    branches:
     - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
        with: 
          path: './'
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '12' # while 14+ technically works, it's 25-50x slower at running native-doc-tooling
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        if: env.key != null
        with:
          key: ${{ secrets.NATIVE_DEPLOY_KEY }}
          known_hosts: ${{ secrets.NATIVE_DEPLOY_KNOWN_HOSTS }}
      - name: Acquire latest compat file
        env:
          NATIVE_DEPLOY_URL: ${{ secrets.NATIVE_DEPLOY_URL }}
        run: |
          mkdir ./in
          rsync -q --ignore-missing-args $NATIVE_DEPLOY_URL/natives_global_client_compat.lua ./in/natives_global_client_compat.lua
      - name: Run build
        run: |
          set -xe
          bash ./.ci/setup-builder
          bash ./.ci/run-deploy
      - name: Deploy
        if: env.NATIVE_DEPLOY_URL != null
        env:
          NATIVE_DEPLOY_URL: ${{ secrets.NATIVE_DEPLOY_URL }}
        run: |
          rsync -rq --delete-after --exclude=*compat.lua* -e 'ssh -p 10865' ./out/ $NATIVE_DEPLOY_URL
          rsync -rqb --backup-dir=./ --suffix=.bak -e 'ssh -p 10865' --include=*compat.lua --exclude=* ./out/ $NATIVE_DEPLOY_URL
